services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nba_user
      POSTGRES_PASSWORD: nba_pass
      POSTGRES_DB: nba_analises
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
